#!/bin/bash

DOCKER_USERNAME=klutzer
APPLICATION_NAME='personal-website:4.0.1'

start_db() {
    docker run -e POSTGRES_PASSWORD=password -e POSTGRES_USER=personalwebsite -p 5432:5432 -d postgres
}

start_web() {
 	npm --prefix ./web install
	npm --prefix ./web run start   
}

start_server() {
    cd server && ENV=prod RATE_LIMIT=1000 DB_PASSWORD=password DB_USER=personalwebsite DB_NAME=personalwebsite DB_HOST=localhost DB_PORT=5432 DB_SSL_MODE=disable PORT=80 STATIC_DIR=../public go run ./cmd/main.go ./cmd/env.go ./cmd/errors.go
}

build_web() { 
    npm --prefix ./web install
	npm --prefix ./web run build
}

build() {
    npm --prefix ./web install
	npm --prefix ./web run build
	docker buildx build --push --platform linux/amd64 --tag ${DOCKER_USERNAME}/${APPLICATION_NAME} .
}

push() {
	docker push ${DOCKER_USERNAME}/${APPLICATION_NAME}
}

if [[ "$1" == "start-web" ]]; then 
    start_web
    exit 0
elif [[ "$1" == "start-db" ]]; then 
    start_db
    exit 0
elif [[ "$1" == "start-server" ]]; then 
    start_server
    exit 0
elif [[ "$1" == "build" ]]; then
    build
    exit 0
elif [[ "$1" == "build-web" ]]; then
    build_web
    exit 0
fi

echo "Options are $0 start-db|start-web|start-server|build|build-web"
exit 1
 