# This workflow will build test and lint the server and web code when a PR is opened or a commit is pushed to the main branch.
name: PersonalWebsite-PRCI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    # Setup node and a cache for dependencies
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: web/package-lock.json

    # Install Just
    - uses: extractions/setup-just@v3
      name: Install Just
      with:
        just-version: '1.40.0'

    # Build Web
    - name: Build the Docker image
      run: just build-web